services:
  nginx:
    build:
      dockerfile: ./src/nginx.Dockerfile
      context: .
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    networks: 
        - topnet
    depends_on:
      - github-topsters-api

  github-topsters-api:
    container_name: github-topsters-api
    depends_on:
      - sqlserver
    build: ./src
    ports:
      - 8080:80
      - 8081:443
    networks: 
        - topnet
    environment:
      ASPNETCORE_ENVIRONMENT: Docker

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: topsters@123
    networks: 
        - topnet

networks: 
    topnet:
        driver: bridge